"""Technology-neutral process catalog (workflows, work products, roles, guidance).

Source: process/areas/*.yaml. Checks referential integrity against the catalog
itself plus the SCORE process-ID snapshot, enforces the WF/WP/RWE rules, and
renders Sphinx-needs RST (one adapter among possible others).
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from .model import QpmError, load_yaml

LIST_FIELDS = ("supported_by", "input", "output", "contains", "has")


def load_catalog(area_dir: str | Path) -> list[dict[str, Any]]:
    areas = []
    for p in sorted(Path(area_dir).glob("*.yaml")):
        doc = load_yaml(p)
        doc["_source"] = str(p)
        areas.append(doc)
    if not areas:
        raise QpmError(f"no process areas in {area_dir}")
    return areas


def load_external_ids(path: str | Path) -> set[str]:
    return {l.strip() for l in Path(path).read_text(encoding="utf-8").splitlines()
            if l.strip() and not l.startswith("#")}


def _ids(areas):
    for a in areas:
        for key in ("concepts", "roles", "templates", "workproducts", "workflows"):
            for item in a.get(key) or []:
                yield a, key, item["id"]


def check_catalog(areas: list[dict[str, Any]], external: set[str]) -> list[str]:
    """Return a list of problems (empty == OK)."""
    errs: list[str] = []
    local: dict[str, str] = {}
    for a, key, i in _ids(areas):
        if i in local:
            errs.append(f"duplicate id {i} ({local[i]} / {a['area']['id']})")
        if i in external:
            errs.append(f"{i} collides with a SCORE id - use the qx prefix")
        local[i] = a["area"]["id"]
    known = set(local) | external

    def ref(i, ctx, prefix):
        if not i.startswith(prefix):
            errs.append(f"{ctx}: '{i}' should start with '{prefix}'")
        elif i not in known:
            errs.append(f"{ctx}: unresolved reference '{i}'")

    produced: set[str] = set()
    used_roles: set[str] = set()
    for a in areas:
        aid = a["area"]["id"]
        ref(a["area"]["owner"], f"{aid}.owner", "rl__")
        for wp in a.get("workproducts") or []:
            ctx = f"{aid}.{wp['id']}"
            if not wp.get("purpose"):
                errs.append(f"{ctx}: work product needs a purpose")
            if wp.get("concept"):
                ref(wp["concept"], ctx, "doc_concept__")
            if wp.get("template"):
                ref(wp["template"], ctx, "gd_temp__")
            for c in wp.get("complies") or []:
                ref(c, ctx, "std_")
        for wf in a.get("workflows") or []:
            ctx = f"{aid}.{wf['id']}"
            ref(wf["responsible"], ctx, "rl__")
            ref(wf["approved_by"], ctx, "rl__")
            if wf["responsible"] == wf["approved_by"]:
                errs.append(f"{ctx}: responsible and approver must differ (four-eyes)")
            for r in wf.get("supported_by") or []:
                ref(r, ctx, "rl__")
            for i in wf.get("input") or []:
                ref(i, ctx, "wp__")
            if not wf.get("output"):
                errs.append(f"{ctx}: workflow must have at least one output WP")
            for o in wf.get("output") or []:
                ref(o, ctx, "wp__")
                produced.add(o)
            for g in wf.get("contains") or []:
                ref(g, ctx, "gd_")
            for h in wf.get("has") or []:
                ref(h, ctx, "doc_")
            roles = {wf["responsible"], wf["approved_by"], *(wf.get("supported_by") or [])}
            used_roles |= roles
            for n, act in enumerate(wf.get("activities") or [], 1):
                if act["by"] not in roles:
                    errs.append(f"{ctx} activity {n}: performer {act['by']} is not responsible/approver/supporter")
    for a in areas:
        for wp in a.get("workproducts") or []:
            if wp["id"] not in produced:
                errs.append(f"{a['area']['id']}.{wp['id']}: no workflow outputs this work product")
        for r in a.get("roles") or []:
            if r["id"] not in used_roles:
                errs.append(f"{a['area']['id']}.{r['id']}: role not used by any workflow")
    return errs


# ------------------------------------------------------------------ RST adapter
def _hdr(text: str, ch: str) -> str:
    return f"{text}\n{ch * len(text)}\n"


def _opt(name: str, val: Any) -> str:
    if not val:
        return ""
    if isinstance(val, list):
        val = ", ".join(val)
    return f"   :{name}: {val}\n"


def _indent(text: str, n: int = 3) -> str:
    pad = " " * n
    return "\n".join(pad + l if l.strip() else "" for l in text.strip().splitlines())


HEADER = (".. Generated by `qpm render-process` from {src} - DO NOT EDIT.\n"
          ".. Edit the YAML source and re-render; CI fails on drift.\n\n")


def render_area(a: dict[str, Any]) -> dict[str, str]:
    ar = a["area"]
    aid = ar["id"]
    src = Path(a["_source"]).as_posix().split("/process/", 1)[-1]
    src = f"process/{src}" if not src.startswith("process/") else src
    files: dict[str, str] = {}
    h = HEADER.format(src=src)

    # index
    idx = h + f".. _qx_area_{aid}:\n\n" + _hdr(ar["title"], "#") + "\n"
    idx += ar["purpose"].strip() + "\n\n"
    idx += f"* **Tier:** {ar['tier']}\n* **Owner:** :need:`{ar['owner']}`\n"
    idx += f"* **Standards:** {', '.join(ar.get('standards') or [])}\n\n"
    for c in a.get("concepts") or []:
        idx += f".. doc_concept:: {c['title']}\n   :id: {c['id']}\n   :status: valid\n   :version: 1\n   :tags: {aid}\n\n"
        idx += _indent(c["body"]) + "\n\n"
    idx += ".. toctree::\n   :maxdepth: 1\n\n   workflows\n   workproducts\n   roles\n   guidance\n"
    files["index.rst"] = idx

    # workflows
    wf_txt = h + _hdr(f"{ar['title']} Workflows", "#") + "\n"
    wf_txt += (".. needflow::\n"
               f"   :filter: \"{aid}\" in tags and type in ['workflow', 'workproduct']\n"
               "   :link_types: input, output\n   :show_link_names:\n\n")
    for wf in a.get("workflows") or []:
        wf_txt += f".. workflow:: {wf['title']}\n   :id: {wf['id']}\n   :status: valid\n   :version: 1\n"
        wf_txt += f"   :tags: {aid}\n"
        for f in ("responsible", "approved_by") + LIST_FIELDS:
            wf_txt += _opt(f, wf.get(f))
        wf_txt += "\n"
        if wf.get("description"):
            wf_txt += _indent(wf["description"]) + "\n\n"
        if wf.get("activities"):
            wf_txt += "   .. list-table:: Activities (RWE)\n      :header-rows: 1\n      :widths: 5 70 25\n\n"
            wf_txt += "      * - #\n        - Activity\n        - Performed by\n"
            for n, act in enumerate(wf["activities"], 1):
                wf_txt += f"      * - {n}\n        - {act['step']}\n        - :need:`{act['by']}`\n"
            wf_txt += "\n"
    files["workflows.rst"] = wf_txt

    # work products (purpose / concept / template triad)
    wp_txt = h + _hdr(f"{ar['title']} Work Products", "#") + "\n"
    for wp in a.get("workproducts") or []:
        wp_txt += f".. workproduct:: {wp['title']}\n   :id: {wp['id']}\n   :status: valid\n   :version: 1\n"
        wp_txt += f"   :tags: {aid}\n"
        wp_txt += _opt("complies", wp.get("complies"))
        wp_txt += _opt("has", wp.get("concept"))
        wp_txt += _opt("contains", wp.get("template"))
        wp_txt += "\n   **Purpose:** " + " ".join(wp["purpose"].split()) + "\n\n"
    files["workproducts.rst"] = wp_txt

    # roles
    rl_txt = h + _hdr(f"{ar['title']} Roles", "#") + "\n"
    for r in a.get("roles") or []:
        rl_txt += f".. role:: {r['title']}\n   :id: {r['id']}\n   :status: valid\n   :version: 1\n   :tags: {aid}\n\n"
        rl_txt += _indent(r["description"]) + "\n\n"
    files["roles.rst"] = rl_txt

    # guidance / templates
    gd_txt = h + _hdr(f"{ar['title']} Guidance", "#") + "\n"
    for t in a.get("templates") or []:
        gd_txt += f".. gd_temp:: {t['title']}\n   :id: {t['id']}\n   :status: valid\n   :version: 1\n   :tags: {aid}\n\n"
        gd_txt += f"   Template file: ``{t['file']}``\n\n"
    files["guidance.rst"] = gd_txt
    return files


def render_catalog(areas: list[dict[str, Any]]) -> dict[str, str]:
    """Return {relative_path: content} for docs/process_areas/."""
    out: dict[str, str] = {}
    toc = []
    for a in areas:
        aid = a["area"]["id"]
        for name, txt in render_area(a).items():
            out[f"{aid}/{name}"] = txt
        toc.append(f"   {aid}/index")
    out["index.rst"] = (HEADER.format(src="process/areas/*.yaml") + ".. _qx_process_areas:\n\n"
                        + _hdr("Qorix Process Areas", "#") + "\n"
                        "Process areas added by the Qorix tier on top of the Eclipse SCORE process areas.\n\n"
                        ".. toctree::\n   :maxdepth: 2\n\n" + "\n".join(toc) + "\n")
    return out
