"""Generated evidence: tailoring report, upstream proposal, needs lint."""
from __future__ import annotations

import difflib
import json
from collections import Counter
from pathlib import Path
from typing import Any

from .adapters import sphinx_needs
from .compose import compose
from .expr import evaluate
from .model import dump_yaml, load_yaml


# ------------------------------------------------------------------ tailoring report
def tailoring_report_rst(m: dict[str, Any], unsupported: list[dict[str, Any]]) -> str:
    p = m.get("project") or {}
    title = f"Process Tailoring Report - {p.get('name', 'organisation')}"
    out = [".. Generated by `qpm compose` - DO NOT EDIT.", "", title, "#" * len(title), ""]
    out += ["Tier chain", "==========", ""]
    for t in m["tiers"]:
        out.append(f"{t['rank']}. **{t['id']}** ({t['kind']}) - {t['title']}")
    out.append("")
    if p:
        integ = p.get("integrity", {})
        out += ["Integrity profile", "=================", "",
                f"* ASIL ceiling: **{integ.get('asil_max', '-')}**",
                f"* CAL ceiling: **{integ.get('cal_max', '-')}**",
                f"* ASPICE target capability level: **{integ.get('aspice_target_level', '-')}**",
                f"* Products: {', '.join(p.get('products') or []) or '-'}",
                f"* Process areas: {', '.join(p.get('process_areas') or [])}", ""]
    origin = Counter(v for k, v in m["provenance"].items() if k.count(".") == 1 and k.startswith("element_types."))
    out += ["Element types by origin", "=======================", ""]
    out += [f"* {tier}: {n}" for tier, n in origin.items()] + [""]
    out += ["Operations log", "==============", "", ".. list-table::", "   :header-rows: 1",
            "   :widths: 15 20 25 10 30", "", "   * - Tier", "     - Operation", "     - Target",
            "     - Upstream", "     - Rationale"]
    for e in m["tailoring_log"]:
        out += [f"   * - {e['tier']}", f"     - {e['op']}", f"     - ``{e['target']}``",
                f"     - {e['upstream'] or '-'}", f"     - {' '.join((e['rationale'] or '-').split())}"]
    out.append("")
    if unsupported:
        out += ["Rules enforced outside Sphinx-needs", "===================================", "",
                "Not expressible in docs-as-code graph checks; enforced by ``qpm lint-needs``:", ""]
        out += [f"* ``{r['id']}`` - {r.get('explanation', '')}" for r in unsupported] + [""]
    return "\n".join(out)


# ------------------------------------------------------------------ upstream (Qorix Fork)
def export_upstream(base: str, overlay: str, score_yaml: str, out_dir: str | Path) -> dict[str, Any]:
    """Build SCORE metamodel with only `upstream: candidate` ops applied, plus diff + PR text."""
    out_dir = Path(out_dir)
    ov = load_yaml(overlay)
    cand = [op for op in ov.get("operations") or [] if op.get("upstream") == "candidate"]
    ov["operations"] = cand
    tmp = out_dir / "_candidate_overlay.qpm.yaml"
    dump_yaml(ov, tmp)
    m = compose([base, tmp])
    tmp.unlink()
    emitted, _ = sphinx_needs.emit(m)
    original = load_yaml(score_yaml)
    a = dump_yaml(original).splitlines(keepends=True)
    b = dump_yaml(emitted).splitlines(keepends=True)
    diff = "".join(difflib.unified_diff(a, b, "score/metamodel.yaml", "qorix-fork/metamodel.yaml"))
    dump_yaml(emitted, out_dir / "metamodel.yaml")
    (out_dir / "metamodel.diff").write_text(diff, encoding="utf-8")
    pr = ["# Proposal: Qorix process extensions for Eclipse SCORE", "",
          "Generated by `qpm export-upstream` from the Qorix overlay. Each change is additive",
          "(superset rule), so existing SCORE content remains valid.", "", "## Changes", ""]
    for op in cand:
        tgt = op.get("name") or op.get("attribute") or op.get("rule", {}).get("id")
        pr.append(f"- **{op['op']}** `{tgt}` - {' '.join((op.get('rationale') or '').split())}")
    pr += ["", "## Diff", "", "See `metamodel.diff`.", ""]
    (out_dir / "PR_DESCRIPTION.md").write_text("\n".join(pr), encoding="utf-8")
    return {"operations": len(cand), "diff_lines": diff.count("\n")}


# ------------------------------------------------------------------ needs.json lint
def _iter_needs(needs_json: dict[str, Any]):
    versions = needs_json.get("versions") or {}
    cur = needs_json.get("current_version")
    ver = versions.get(cur) if cur in versions else (next(iter(versions.values())) if versions else {})
    return (ver.get("needs") or {}).values()


def lint_needs(m: dict[str, Any], needs_path: str | Path) -> list[str]:
    data = json.loads(Path(needs_path).read_text(encoding="utf-8"))
    problems: list[str] = []
    rules = [r for r in m["rules"] if r["kind"] == "attribute_required_if"]
    for need in _iter_needs(data):
        for r in rules:
            if need.get("type") not in r["applies_to"]["types"]:
                continue
            if "where" in r["applies_to"] and not evaluate(r["applies_to"]["where"], need):
                continue
            for attr in r["require_attributes"]:
                if not need.get(attr):
                    problems.append(f"{need['id']}: {r['id']}: missing '{attr}' - {r.get('explanation', '')}")
    return problems
