#!/usr/bin/env bash
# Regenerate all committed, generated content. CI runs this and fails on `git diff`.
set -euo pipefail
cd "$(dirname "$0")/../.."          # repository root (= system of interest)
export PYTHONPATH=prod/realization/qpm
B=prod/concepts/tiers/00_qorix_base/qorix_base.qpm.yaml
Q=prod/concepts/tiers/10_qorix/qorix_overlay.qpm.yaml
T=prod/dist                         # site pages for the distributions (tailoring reports)

# assemblies (prod/assemblies/<cluster>/<process>/) + needs/ -> assembly, cluster, Assemblies and Needs pages
python3 -m qpm render-process --assemblies prod/assemblies --standards needs/standards.yaml --out-dir prod

# tiers + project distributions (dist/) -> composed models and tailoring reports
mkdir -p "$T"
python3 -m qpm compose --tier "$B" --tier "$Q" --out-dir build/qorix
cp build/qorix/tailoring_report.rst "$T/qorix.rst"
toc="qorix"
for t in dist/*/tailoring.qpm.yaml; do
  p=$(basename "$(dirname "$t")"); [[ "$p" == _* ]] && continue
  python3 -m qpm compose --tier "$B" --tier "$Q" --tier "$t" --out-dir "build/$p"
  cp "build/$p/tailoring_report.rst" "$T/$p.rst"
  toc="$toc $p"
done
{ echo ".. Generated by prod/realization/regen.sh from dist/ - DO NOT EDIT."; echo; echo ".. _qx_dist:"; echo
  echo "Dist"; echo "####"; echo
  echo "One distribution per project: the composed process (Qorix base + Qorix overlay + project"
  echo "tailoring) and its tailoring report. Sources: \`\`dist/<project>/tailoring.qpm.yaml\`\`."; echo
  echo ".. toctree::"; echo "   :maxdepth: 1"; echo
  for p in $toc; do echo "   $p"; done; } > "$T/index.rst"
