"""Import an Eclipse SCORE docs-as-code ``metamodel.yaml`` into a QPM base tier.

This is how the SCORE process baseline enters the framework: SCORE stays the
upstream source of truth, the importer translates it into neutral form, and
every Qorix tier is expressed as operations on top of it.
"""
from __future__ import annotations

from typing import Any

from ..model import QPM_VERSION, pattern_to_attr


def _split(csv: str) -> list[str]:
    return [p.strip() for p in csv.split(",") if p.strip()]


def _attrs(mandatory: dict | None, optional: dict | None) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for name, pat in (mandatory or {}).items():
        out[name] = pattern_to_attr(pat, True)
    for name, pat in (optional or {}).items():
        out[name] = pattern_to_attr(pat, False)
    return out


def _rels(mandatory: dict | None, optional: dict | None) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for name, tgt in (mandatory or {}).items():
        out[name] = {"required": True, "targets": _split(tgt)}
    for name, tgt in (optional or {}).items():
        out[name] = {"required": False, "targets": _split(tgt)}
    return out


def import_score_metamodel(score: dict[str, Any], source: dict[str, Any] | None = None) -> dict[str, Any]:
    base_opts = score.get("needs_types_base_options") or {}
    tier: dict[str, Any] = {
        "qpm": QPM_VERSION,
        "tier": {
            "id": "score-base",
            "kind": "base",
            "title": "Eclipse SCORE process baseline (imported)",
            "description": "Generated by `qpm import-score`. Do not edit by hand; re-import on SCORE upgrade.",
            "owner": "Eclipse SCORE (upstream)",
            "source": source or {},
        },
        "defaults": {"attributes": _attrs(base_opts.get("mandatory_options"), base_opts.get("optional_options"))},
        "element_types": {},
        "relation_types": {},
        "rules": [],
        "lint": {"forbidden_words": []},
    }

    for name, t in (score.get("needs_types") or {}).items():
        et: dict[str, Any] = {"title": t["title"], "prefix": t.get("prefix", f"{name}__")}
        if "parts" in t:
            et["id_parts"] = t["parts"]
        if t.get("description"):
            et["description"] = t["description"]
        et["tags"] = list(t.get("tags") or [])
        et["attributes"] = _attrs(t.get("mandatory_options"), t.get("optional_options"))
        et["relations"] = _rels(t.get("mandatory_links"), t.get("optional_links"))
        pres = {k: t[k] for k in ("color", "style") if k in t}
        if pres:
            et["presentation"] = pres
        tier["element_types"][name] = et

    for name, l in (score.get("needs_extra_links") or {}).items():
        tier["relation_types"][name] = {"forward": l["outgoing"], "reverse": l["incoming"]}

    for rid, g in (score.get("graph_checks") or {}).items():
        needs = g["needs"]
        qkey = "check_all" if "check_all" in g else "check_one"
        ((rel, expect),) = g[qkey].items()
        applies: dict[str, Any] = {"types": _split(needs.get("include", ""))}
        if needs.get("exclude"):
            applies["exclude"] = _split(needs["exclude"])
        if "condition" in needs:
            applies["where"] = needs["condition"]
        rule = {
            "id": rid,
            "kind": "graph",
            "applies_to": applies,
            "check": {"quantifier": "all" if qkey == "check_all" else "one", "relation": rel, "expect": expect},
            "explanation": g.get("explanation", ""),
            "severity": "info" if g.get("info_only") else "warning",
        }
        tier["rules"].append(rule)

    for cid, c in (score.get("prohibited_words_checks") or {}).items():
        entry = {"id": cid, "fields": {k: list(v) for k, v in c.items() if k != "types"}}
        if c.get("types"):
            entry["applies_to_tags"] = list(c["types"])
        tier["lint"]["forbidden_words"].append(entry)

    return tier
